spring.application.name=03-SB-EmailService

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srjaiswal0069@gmail.com
spring.mail.password=cqnl stdh iwgk ugcm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.requires=true